"""orators table

Revision ID: 160e22df8e56
Revises: 
Create Date: 2019-02-02 21:04:03.863559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160e22df8e56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('age', sa.String(length=120), nullable=True),
    sa.Column('info', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orator_name'), 'orator', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orator_name'), table_name='orator')
    op.drop_table('orator')
    # ### end Alembic commands ###
