"""added job and photo columns to Orator

Revision ID: 6a809e8729a0
Revises: ef29204ae93f
Create Date: 2019-02-11 21:12:24.057195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a809e8729a0'
down_revision = 'ef29204ae93f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orator', sa.Column('job', sa.String(length=120), nullable=True))
    op.add_column('orator', sa.Column('photo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orator', 'photo')
    op.drop_column('orator', 'job')
    # ### end Alembic commands ###
